"""
core/api_client.py
------------------
Lightweight HTTP publisher for the DuctSense FastAPI Sync Service.

Publishes a completed walkthrough report to POST /walkthroughs so that
the existing React dashboard can display live pipeline results.

Design decisions
----------------
* Uses only the Python standard library (urllib.request / urllib.error)
  — no new dependencies introduced.
* A single configuration constant (API_BASE_URL) is the only place the
  backend address is defined.
* Failures are non-fatal: the caller receives a clear warning string
  instead of an exception so that the pipeline never crashes because
  the dashboard backend is unavailable.
* Sensor-evidence fields (thermal_confidence, pressure_differential_pa,
  normalized_pressure, audio_confidence) are forwarded when present.
  normalized_pressure is derived using the same 100 Pa cap that
  fusion_logic.py already uses — no competing formula.
"""

import json
import urllib.request
import urllib.error

# ── Configuration ─────────────────────────────────────────────────────────────
# Change this value if the FastAPI backend is hosted elsewhere.
API_BASE_URL = "http://localhost:8000"

_WALKTHROUGHS_ENDPOINT = API_BASE_URL + "/walkthroughs"

# Must stay identical to fusion_logic.PRESSURE_NORMALIZATION_CAP_PA.
# Normalization: normalized_pressure = min(pressure_pa / cap, 1.0)
_PRESSURE_NORMALIZATION_CAP_PA = 100.0


# ── Public API ────────────────────────────────────────────────────────────────

def publish_walkthrough(
    walkthrough_id: str,
    date: str,
    events: list,
) -> None:
    """
    POST a completed walkthrough report to the FastAPI Sync Service.

    Parameters
    ----------
    walkthrough_id : str
        The UUID generated by storage.start_walkthrough() for this session.
    date : str
        ISO-8601 date string (YYYY-MM-DD) representing when the walkthrough ran.
    events : list[dict]
        Leak-event dicts as returned by storage.get_events_for_walkthrough().
        Required fields: position_m, leak_confidence, timestamp.
        Optional sensor-evidence fields forwarded when present:
          thermal_confidence, pressure_differential_pa, audio_confidence.
        normalized_pressure is derived from pressure_differential_pa using the
        same cap constant as fusion_logic.py.

    Notes
    -----
    POST /walkthroughs payload shape:
        {
            "walkthrough_id": "<uuid>",
            "date":           "<YYYY-MM-DD>",
            "events": [
                {
                    "position_m":               float,
                    "leak_confidence":          float,
                    "timestamp":                float,
                    "thermal_confidence":       float | null,
                    "pressure_differential_pa": float | null,
                    "normalized_pressure":      float | null,
                    "audio_confidence":         float | null
                },
                ...
            ]
        }

    The INSERT OR REPLACE behaviour on the backend means sending the same
    walkthrough_id a second time safely overwrites the previous record —
    no duplicate rows are created.

    Failures are non-fatal: all network errors print a warning and return
    normally so the pipeline is never aborted because the backend is offline.
    """
    def _build_event(e: dict) -> dict:
        """Build one event dict, adding normalized_pressure when available."""
        ev: dict = {
            "position_m":      float(e["position_m"]),
            "leak_confidence": float(e["leak_confidence"]),
            "timestamp":       float(e["timestamp"]),
        }
        # Forward sensor evidence when present in the stored row.
        if e.get("thermal_confidence") is not None:
            ev["thermal_confidence"] = float(e["thermal_confidence"])
        if e.get("pressure_differential_pa") is not None:
            pa = float(e["pressure_differential_pa"])
            ev["pressure_differential_pa"] = pa
            # Derive normalized_pressure with the same formula fusion_logic uses.
            ev["normalized_pressure"] = min(pa / _PRESSURE_NORMALIZATION_CAP_PA, 1.0)
        if e.get("audio_confidence") is not None:
            ev["audio_confidence"] = float(e["audio_confidence"])
        return ev

    payload = {
        "walkthrough_id": walkthrough_id,
        "date": date,
        "events": [_build_event(e) for e in events],
    }

    body = json.dumps(payload).encode("utf-8")
    req  = urllib.request.Request(
        _WALKTHROUGHS_ENDPOINT,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
            text   = resp.read().decode("utf-8")
        print(f"  [API] Walkthrough published -> {_WALKTHROUGHS_ENDPOINT} "
              f"(HTTP {status})")
        print(f"  [API] Response: {text}")
    except urllib.error.HTTPError as exc:
        body_text = exc.read().decode("utf-8", errors="replace")
        print(f"Warning: Could not publish walkthrough to FastAPI: "
              f"HTTP {exc.code} - {body_text}")
    except urllib.error.URLError as exc:
        print(f"Warning: Could not publish walkthrough to FastAPI: "
              f"{exc.reason}")
    except Exception as exc:
        print(f"Warning: Could not publish walkthrough to FastAPI: {exc}")
